### PR TITLE
Use web3.storage compatible CID's

### PR DESCRIPTION
**Pull request by thewtex**
These CIDs are different because they are created with different block
sizes to be compatible with the blocks used by https://web3.storage.

Resulting root CID:
bafybeialgmdqikskc56dhy2xrnio2te23xdzqdm77wtqxpxybr3ys5cpli

Script used:

```

from pathlib import Path
import subprocess
import os
import json

publications_dir = Path('/home/matt/src/InsightJournal/data/publications')

def add_cid(pub):
    revs = list(pub.iterdir())

    articles = [None,]*len(revs)
    for index, rev in enumerate(revs):
        article_pdf_file = rev / 'article.pdf'
        print(rev)
        if not article_pdf_file.exists():
            print('MISSING')
            continue
        cid = subprocess.check_output(['ipfs', 'add', '--cid-version', '1', '-Q', '--raw-leaves', '--hidden', '-s', 'size-1048576', str(article_pdf_file)])
        articles[index] = str(cid.decode().strip())
    print(articles)
    metadata_json = publications_dir / pub / 'metadata.json'
    print(metadata_json)
    with open(str(metadata_json), 'r') as fp:
        metadata = json.load(fp)
    metadata['publication']['articles'] = articles
    with open(str(metadata_json), 'w') as fp:
        json.dump(metadata, fp, sort_keys=True, indent='  ')

for pub in Path('.').iterdir():
    if pub.is_dir():
        add_cid(pub)
```

### CODE REVIEW

**Comment by phcerdan** [comment]
> article_pdf_file = rev / 'article.pdf'

Is this assuming the articles files are named `article`?

This is not always the case, also sometimes there are more than one pdf. Publication 104 is a en example of both:
https://data.kitware.com/#collection/5cb75e388d777f072b41e8db/folder/5cca077c8d777f072b808e27

image

**Comment by thewtex** [comment]
Yes, the naming of the article files was inconsistent, previously, which was annoying.

To get the new layout:

```
ipfs get bafybeialgmdqikskc56dhy2xrnio2te23xdzqdm77wtqxpxybr3ys5cpli
```

In the new layout, they are stored on disk as *article.pdf*. When downloaded from the website, we give them a consistent, descriptive name based on the publication title.

**Comment by phcerdan** [comment]
I think we need to supervise manually the case when multiple pdfs are present.
For the publication 104, we have uploaded a supplemental pdf, not the main article.
In this sense, I think adding a way supplemental subfolder to each revision would be good (if there is any)

Also, the data stored was trimmed from `11G` in https://data.kitware.com/#collection/5cb75e388d777f072b41e8db to `1.3G` in ipfs.

I guess the difference would be in supplemental data and code?

**Review by phcerdan — APPROVED** [review]
Great, let's merge!. But we have to handle the case of multiple pdf, and get a strategy on how to handle supplemental pdfs and other data (code, test images, etc)

**Comment by thewtex** [comment]
> Great, let's merge!. But we have to handle the case of multiple pdf, and get a strategy on how to handle supplemental pdfs and other data (code, test images, etc)

:+1: :rocket:

**Pull request merged**
