### PR TITLE
Add article CID's

### PR DESCRIPTION
**Pull request by thewtex**
Two scripts are executed to extract the article CID's.

First, the PDF's are extracted and put into their own file hierarchy.
For simplicity, if a publication had multiple PDF's, they are
concatenated.

```python
  #!/usr/bin/env python3

  from pathlib import Path
  import shutil
  import subprocess

  output_dir = Path('/home/matt/data/ij-articles')
  if not output_dir.exists():
      output_dir.mkdir(parents=True)

  def extract_articles(rev_path):
      output_rev_dir = output_dir / rev_path
      if not output_rev_dir.exists():
	  output_rev_dir.mkdir(parents=True)
      articles = list(rev_path.glob('*.pdf'))
      articles.sort()
      if len(articles) == 0:
	  pass
      elif len(articles) == 1:
	  shutil.copy2(str(articles[0]), str(output_rev_dir / 'article.pdf'))
      else:
	  subprocess.check_call(["pdftk",] + [str(a) for a in articles] + ["cat",
	      "output", str(output_rev_dir / 'article.pdf')])

  for pub in Path('.').iterdir():
      if pub.is_dir():
	  for rev in pub.iterdir():
	      if rev.is_dir():
		  print(rev)
		  extract_articles(rev)
```

Second, the CID's are generated and added to the metadata.json files.
```python
#!/usr/bin/env python3

from pathlib import Path
import subprocess
import os
import json

publications_dir = Path('/home/matt/src/InsightJournal/data/publications')

def add_cid(pub):
    revs = list(pub.iterdir())

    articles = [None,]*len(revs)
    for index, rev in enumerate(revs):
        article_pdf_file = rev / 'article.pdf'
        print(rev)
        if not article_pdf_file.exists():
            print('MISSING')
            continue
        cid = subprocess.check_output(['ipfs', 'add', '--cid-version', '1', '-Q', str(article_pdf_file)])
        articles[index] = str(cid.decode().strip())
    print(articles)
    metadata_json = publications_dir / pub / 'metadata.json'
    print(metadata_json)
    with open(str(metadata_json), 'r') as fp:
        metadata = json.load(fp)
    metadata['publication']['articles'] = articles
    with open(str(metadata_json), 'w') as fp:
        json.dump(metadata, fp, sort_keys=True, indent='  ')

for pub in Path('.').iterdir():
    if pub.is_dir():
        add_cid(pub)
```

### CODE REVIEW

**Comment by phcerdan** [comment]
Looks good!
Thinking out loud, not sure if we should add the revision number to the articles.
```
articles: {
   {
   revision:0,
   datas: [{
       metadata: 'main',
       cid: 'aaaaaaa'
     },
     {
       metadata: 'code',
       cid: 'bbbbbbb'
      }]
    },
    {
   revision:1,
   datas: [{
       metadata: 'main',
       cid: 'asdasd'
     },
     {
       metadata: 'code',
       cid: 'asdasd'
      }]
    }
}
```
I like a "rolling" publication instead of a by "revision/release/draft" number. However that approach is the standard.

**Comment by thewtex** [comment]
Ah, yes, rolling is good. I was working with the existing structures where we have `handles` as an array where each entry is a revision. When we have explicit revisions that can be updated, we get both a living article and immutable revisions that can always be revisited and examined. That said, we could organize the per-revision data better as suggested (and also ensure that all per-revision data has the same length). It is simpler to have the revision number indicated by the array index. So, I am thinking:

```
source_code_git_repo: "https://github.com/InsightSoftwareConsortium/ITKTotalVariation",
revisions: [
  {
    handle: "http://hdl.handle.net/4830/1",
    article: "bafycid1a",
    source_code: "bafycid2a",
    source_code_git_ref: "abc123",
    dataset: "bafycid3a",
    dapp: "bafycid4a",
    doi: "doi://crossref-citable/1"
   },
  {
    handle: "http://hdl.handle.net/4830/2",
    article: "bafycid2a",
    source_code: "bafycid2a",
    source_code_git_ref: "abc123a",
    dataset: "bafycid3a",
    dapp: "bafycid4a",
    doi: "doi://crossref-citable/2"
   },
]
```

- `handle`: For new articles, we will only be minting doi's, but we need to keep the handle references around.
- `article`: The PDF prose
- `source_code`: An IPFS archive of the Git tree
- `source_code_git_ref`: The git hash or tag
- `dataset`: The IPFS data directory
- `dapp`: An IPFS directory for a distributed web app that uses the data and code to interactively reproduce/verify the results
- `doi`: The versioned crossref DOI

**Comment by phcerdan** [comment]
I like that structure, good to have it in mind for the future! Thanks @thewtex

**Review by phcerdan — APPROVED** [review]
:tada:

**Pull request merged**
