### PR TITLE
Correct publication 176 article CID

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@phcerdan not sure what happened here, but there is only 1 revision, when there should be 8. :confused:

**Comment by phcerdan** [comment]
Might be something wrong with the introduction of revisions.
I found at [a1c22ee](a1c22ee1868102675795f25e3cee0c82bd763196) that only 15 publications have more than one revision. In those, the handles were mostly wrong for initial revisions, and only correct for the last one.
So I reduced the revisions of these 15 publication to only one. Choosing manually the right handle, pdf and source code.
This particular case, the 176 didn't have more than 1 revision, so it was untouched.

**Comment by thewtex** [comment]
@phcerdan makes sense. :+1: For these 15 publications, do they have this same invalid CID issue?

**Comment by phcerdan** [comment]
> For these 15 publications, do they have this same invalid CID issue?

No, they are ok (after the manual selection). See for example [publication 10](https://www.insight-journal.org/browse/publication/10) or 11.

**Pull request merged**
