### PR TITLE
 Add redirect for RIRE

### PR DESCRIPTION
**Pull request by thewtex**
The site was previously located at

  https://insight-journal.org/rire/index.php

Now sustainably hosted at

  https://rire.insight-journal.org/

### CODE REVIEW

**Comment by thewtex** [comment]
Closes #56

**Comment by thewtex** [comment]
@josephsnyder @jjomier please take a look

**Comment by aylward** [comment]
This is outstanding!!!!  Woo!!!

**Comment by thewtex** [comment]
While this worked locally, there are issues when deployed to IPFS, as the CI build caught. We will need a different approach.

**Comment by thewtex** [comment]
Working now :-) :rocket: :space_invader:

**Pull request merged**
