### PR TITLE
Bump material UI version

### PR DESCRIPTION
**Pull request by bnmajor**
Bumpy Material UI to v5

### CODE REVIEW

**Comment by thewtex** [comment]
@bnmajor thanks!

The homepage seems to have CSS issues?

image

This was observed on the Chrome-base Brave browser. Any ideas?

**Comment by bnmajor** [comment]
@thewtex I'm not sure but I will look into it. Testing in Chrome (Version 96.0.4664.93) and Firefox (Version 95.0) things appear okay though:
homepage

**Comment by bnmajor** [comment]
@thewtex Nevermind, I can recreate this problem. I will get this fixed and ping you when the branch is ready.

**Comment by thewtex** [comment]
@bnmajor added more updates. If there is no objection, I will merge.

**Comment by bnmajor** [comment]
I actually am still seeing some issues with the css, seems that none of the data is being displayed in the tables.

insight_journal

**Comment by bnmajor** [comment]
@thewtex It looks like adding `autoHeight={true}` to the `DataGrid` components fixes the issue so I've added a commit with that change. As long as everything looks good for you as well I'm happy to have this merged in.

**Comment by thewtex** [comment]
@bnmajor Brilliant! :monocle_face:  :clap: :100: :1st_place_medal:  Thank you!

**Pull request merged**
