### PR TITLE
BUG: Add missing revisions to 228 parabolic morphology article

### PR DESCRIPTION
**Pull request by thewtex**
There are 3 revisions to this article. The first revision did not include a PDF. When visiting the page on the deployed website, the PDF never loads.

Copy the metadata to the two other revisions so the latest revision, Revision 3, loads.

### CODE REVIEW

**Comment by thewtex** [comment]
@phcerdan could you please take a look?

The PDF does not currently load for https://doi.org/10.54294/aq68pt

No bueno!

**Comment by phcerdan** [comment]
Sure! Having a look

**Review by phcerdan — APPROVED** [review]
Looking good, how did we lose these revisions?

**Comment by thewtex** [comment]
@phcerdan thanks for the review!

> how did we lose these revisions?

Not sure

**Comment by thewtex** [comment]
Much better:

image

**Pull request merged**
