### PR TITLE
Add data with all publication issues (collections)

### PR DESCRIPTION
**Pull request by phcerdan**
Add data with all publication issues (collections)

Using scripts from:
https://github.com/phcerdan/insightjournal-dev/commit/94af42e21b81ab1006836f2b3e904a93ce692507

Each issue has a field keeping track of the publication that it includes: `publications = [publication_id, ...]`

A publication doesn't need to know in what issue or issues it appears.

### CODE REVIEW

**Comment by phcerdan** [comment]
@thewtex I am guessing gatsby would be able to query two `json` files to combine the information by id.

**Comment by thewtex** [comment]
@phcerdan well done! 🏅 

How do we connect the issue to the data in metadata.json. E.g. looking at publication 553 it has *journal_id* 33, but *id* is missing from all_issue.json? Or should there be another connection?

**Comment by phcerdan** [comment]
> How do we connect the issue to the data in metadata.json

My original intention was to add the field:
 ```
 issues: [issue_id, ...]
 ```
to each `publications/${publication_id}/metadatal.json` where `issue_id` is in this `all_issues.json`.

This way, to know what articles belong to an issue, a query will need to be done to all publications, getting their `issue_id`.

However, seems more reasonable to treat `issue` as a container of publications, so I will add the  field: 
```
publications: [publication_id, ... ]
```
here to `all_issues.json`.

Now, two options regarding the info that appear in `publications/metadata.json`
A) Publication has the mentioned issues field. Easy to query, but there will be repeated information, and chances to get out of sync if a publication, or issue, are deleted.
B) Publication knows nothing about issues. If we want to know about the issues of a publication, we have to query all issues.

I think I prefer the approach B, an element shouldn't keep reference in what containers is placed. Also assuming that an article might be "bundled" in more than one issue.

I don't think every article has to belong to an "issue", we are not printing magazines fortnightly!

I will go for option B for now, adding a publication field to each issue here in `all_issues.json`.

**Comment by phcerdan** [comment]
@thewtex ready to review, each issue now keeps a list of the publication it holds.
Updated commit message

**Comment by thewtex** [comment]
> I think I prefer the approach B, an element shouldn't keep reference in what containers is placed. Also assuming that an article might be "bundled" in more than one issue.

:+1: agreed!

> I don't think every article has to belong to an "issue", we are not printing magazines fortnightly!

Amen! Let's do what makes sense for modern open science.

@phcerdan this is beautiful. Nice to have *all_issues.json*, the content, including titles, description, and the relationship set up this way with publications. Looking ahead, this should work nicely, but we can also tweak if the need arises.

**Review by thewtex — APPROVED** [review]

**Pull request merged**
